### ISSUE TITLE
Using a non-white background color for project section will alterate the design

### ISSUE THREAD

**Issue by createNull** [cobidev/simplefolio#18]
Hello Jacob, 

Try changing the background color for the project section.
I've tried to fix it, but I'm no expert in CSS.

**Comment by cobidev** [comment]
@createNull Hello!!

Sorry for the late response, did you find a way to change the background?

Let me know, so I can help you with that 🙌

**Comment by createNull** [comment]
Yes, you just change the value of the variables in css, especially the white color

**Comment by createNull** [comment]
It's still not fixed, sadly.
I guess closing the issue means you won't bother to fix it which I can understand, but I think you should have stated that in the previous comment.
Cheers!

**Comment by cobidev** [comment]
@createNull I misunderstood your comment, sorry.

Thought you found a way to change the background color for the project section. That's why I closed the issue

If you want to change the background color, just got to src/style/sections/_projects.scss and then in the file, at the beggining just change the background-color and the color as well (color of font) for the entire Project Section.

Let me know if that solves your issue! 👍

**Comment by createNull** [comment]
This is exactly the bug.
I really don't know why aren't you trying to do it, so you can see what happens.

This bug happens in desktop mode only.
I will attach pictures since you're not trying to reproduce it yourself.

![image](https://user-images.githubusercontent.com/23474238/77999912-567c5c00-732b-11ea-9847-a91e7315c461.png)
![image](https://user-images.githubusercontent.com/23474238/77999931-5bd9a680-732b-11ea-8693-379316b9affd.png)
